{
 "title": "Final",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "artillery-node, artillery-gunicorn, artillery-node_replicated, artillery-n9090, artillery-n9091"
   },
   {
    "name": "container",
    "query": "7573_arqsoft_tp1_node_1, 7573_arqsoft_tp1_node_2, 7573_arqsoft_tp1_node_3, 7573_arqsoft_tp1_cadvisor_1, 7573_arqsoft_tp1_grafana_1, 7573_arqsoft_tp1_graphite_1, 7573_arqsoft_tp1_gunicorn_1, 7573_arqsoft_tp1_nginx_1, 7573_arqsoft_tp1_arqsoft_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.*, 'count')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p95, 'P95')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 7700000000), 'Memory')"
    }
   ]
  },
  {
   "title": "Codes QTY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.codes.*)"
    }
   ]
  },
  {
   "title": "Node Replicated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.7573_arqsoft_tp1_node_1.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU_1')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.7573_arqsoft_tp1_node_2.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU_2')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.7573_arqsoft_tp1_node_3.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU_3')"
    }
   ]
  }
 ]
}