{
 "title": "Main dashboard",
 "time": { "from": "2020-05-24T03:04:00.000Z", "to": "2020-05-24T03:08:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "artillery-node, artillery-gunicorn"
   },
   {
    "name": "container",
    "query": "7573_arqsoft_tp1_node_1, 7573_arqsoft_tp1_node_2, 7573_arqsoft_tp1_node_3, 7573_arqsoft_tp1_cadvisor_1, 7573_arqsoft_tp1_grafana_1, 7573_arqsoft_tp1_graphite_1, 7573_arqsoft_tp1_gunicorn_1, 7573_arqsoft_tp1_nginx_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 10737418240), 'Memory')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p95, 'P95')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Cantidad de 200",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.codes.200, '200')"
    }
   ]
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  }
 ]
}