{
 "title": "Diego",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "artillery-node, artillery-gunicorn"
   },
   {
    "name": "container",
    "query": "7573_arqsoft_tp1_node_1, 7573_arqsoft_tp1_node_2, 7573_arqsoft_tp1_node_3, 7573_arqsoft_tp1_cadvisor_1, 7573_arqsoft_tp1_grafana_1, 7573_arqsoft_tp1_graphite_1, 7573_arqsoft_tp1_gunicorn_1, 7573_arqsoft_tp1_nginx_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Max RPS without Timeout",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "multiplySeries(offset(scale(isNonNull(stats.gauges.$server.codes.504), -1), 1), stats.gauges.$server.rps.count)"
    }
   ]
  },
  {
   "title": "Max RPS without Fatal Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "multiplySeries(offset(scale(isNonNull(sumSeries(stats.gauges.$server.codes.500, stats.gauges.$server.errors.*)), -1), 1), stats.gauges.$server.rps.count)"
    }
   ]
  },
  {
   "title": "RPS count without errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(multiplySeries(offset(scale(isNonNull(sumSeries(stats.gauges.$server.codes.504, stats.gauges.$server.errors.*)), -1), 1), stats.gauges.$server.rps.count), 'RPS w/o timeout')"
    },
    {
     "target": "alias(multiplySeries(offset(scale(isNonNull(stats.gauges.$server.errors.*), -1), 1), stats.gauges.$server.rps.count), 'RPS w/o error')"
    }
   ]
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(sumSeries(stats.gauges.$server.codes.5*), 'HTTP5xx')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 10737418240), 'Memory')"
    }
   ]
  }
 ]
}